### ISSUE TITLE
bug: Completion tracking in Pulse dPrep seems to malfunction 

### ISSUE THREAD

**Issue by opgeROBt** [hannesdatta/pulse#35]
Hi Hannes , 

it seems Pulse is bugging out a bit on week 3 and some of the assignments are linked with week 2. 
i.e. I complete a subject in week 2 and it completes another issue in week 3. it seems they are linked. 

Changing this around I now have completed week 2 124% somehow. (great progress!) 
I have included a screenshot below. 

![pulse bug completion](https://user-images.githubusercontent.com/93389499/153762356-107dd36d-db20-41a4-a005-e7d7c4aa6ab1.PNG)

maybe later in the course we will be able to contribute as a class during the course to the repo! : )

**Comment by hannesdatta** [comment]
@opgeROBt, I just pushed [8120a8a](https://github.com/hannesdatta/pulse/commit/8120a8ada26f16b856c3062f76b9b474774515e1) - can you check whether this resolved the bug? I didn't select the most recent event logs (but all of them...). Lemme know please.

**Comment by opgeROBt** [comment]
Hi Hannes, 
thank you for the bug fix, I was curious how it would work with GitHub : ) 
I have checked pulse and it looks like it isn't going over 100% completion anymore. 

I am not able to gain 100% on week 1/2 even though I have completed the topic. But this might be interesting for me to look into and contribute to pulse.  👍

**Comment by hannesdatta** [comment]
@opgeROBt, is this still an issue? Otherwise we can close this thread.

**Comment by opgeROBt** [comment]
@hannesdatta, haven't experienced any issues lately using pulse. 
Thank you for fixing the bug 👍
